version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=aluguel-carros
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: aluguel-carros
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local